// LOCALHOST
###
GET http://localhost:3000/contacts
###
GET http://localhost:3000/contacts/68d4366859ec90c142035cfe
###
GET http://localhost:3000/contacts/68d438b459ec90c142035cff
###
GET http://localhost:3000/contacts/68d43caa59ec90c142035d00

// PRODUCTION
###
GET https://cse-341-b5tl.onrender.com/contacts
###
GET https://cse-341-b5tl.onrender.com/contacts/68d4366859ec90c142035cfe
###
GET https://cse-341-b5tl.onrender.com/contacts/68d438b459ec90c142035cff
###
GET https://cse-341-b5tl.onrender.com/contacts/68d43caa59ec90c142035d00